"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _admin_users_tab from './admin-users-tab.bones.json'
import _boons_page from './boons-page.bones.json'
import _domains_page from './domains-page.bones.json'
import _news_page from './news-page.bones.json'
import _premonitions_page from './premonitions-page.bones.json'
import _surfaceweb_page from './surfaceweb-page.bones.json'

registerBones({
  "admin-users-tab": _admin_users_tab,
  "boons-page": _boons_page,
  "domains-page": _domains_page,
  "news-page": _news_page,
  "premonitions-page": _premonitions_page,
  "surfaceweb-page": _surfaceweb_page,
})
