/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './index.html',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-tint':                   'var(--theme-surface-tint, #ffb3ae)',
        'surface-container-lowest':       'var(--theme-surface-container-lowest, #0e0e0e)',
        'surface-container':              'var(--theme-surface-container, #201f1f)',
        'on-primary-container':           'var(--theme-on-primary-container, #ffc3be)',
        'inverse-on-surface':             'var(--theme-inverse-on-surface, #313030)',
        'secondary-container':            'var(--theme-secondary-container, #474746)',
        'primary':                        'var(--theme-primary, #ffb3ae)',
        'on-primary-fixed':               'var(--theme-on-primary-fixed, #410004)',
        'secondary':                      'var(--theme-secondary, #c8c6c5)',
        'surface-variant':                'var(--theme-surface-variant, #353534)',
        'on-primary-fixed-variant':       'var(--theme-on-primary-fixed-variant, #930014)',
        'on-error-container':             'var(--theme-on-error-container, #ffdad6)',
        'on-tertiary-container':          'var(--theme-on-tertiary-container, #4b3e00)',
        'error-container':                'var(--theme-error-container, #93000a)',
        'on-error':                       'var(--theme-on-error, #690005)',
        'on-secondary':                   'var(--theme-on-secondary, #313030)',
        'tertiary-container':             'var(--theme-tertiary-container, #c8a900)',
        'primary-fixed-dim':              'var(--theme-primary-fixed-dim, #ffb3ae)',
        'on-surface-variant':             'var(--theme-on-surface-variant, #e4beba)',
        'surface-container-low':          'var(--theme-surface-container-low, #1c1b1b)',
        'primary-fixed':                  'var(--theme-primary-fixed, #ffdad7)',
        'on-primary':                     'var(--theme-on-primary, #68000b)',
        'surface':                        'var(--theme-surface, #131313)',
        'background':                     'var(--theme-background, #131313)',
        'on-surface':                     'var(--theme-on-surface, #e5e2e1)',
        'on-secondary-fixed-variant':     'var(--theme-on-secondary-fixed-variant, #474746)',
        'on-background':                  'var(--theme-on-background, #e5e2e1)',
        'secondary-fixed-dim':            'var(--theme-secondary-fixed-dim, #c8c6c5)',
        'outline':                        'var(--theme-outline, #ab8986)',
        'tertiary-fixed':                 'var(--theme-tertiary-fixed, #ffe16d)',
        'tertiary':                       'var(--theme-tertiary, #e9c400)',
        'secondary-fixed':                'var(--theme-secondary-fixed, #e5e2e1)',
        'outline-variant':                'var(--theme-outline-variant, #5b403e)',
        'on-tertiary':                    'var(--theme-on-tertiary, #3a3000)',
        'surface-container-high':         'var(--theme-surface-container-high, #2a2a2a)',
        'surface-dim':                    'var(--theme-surface-dim, #131313)',
        'inverse-surface':                'var(--theme-inverse-surface, #e5e2e1)',
        'on-secondary-container':         'var(--theme-on-secondary-container, #b7b5b4)',
        'surface-bright':                 'var(--theme-surface-bright, #393939)',
        'error':                          'var(--theme-error, #ffb4ab)',
        'on-tertiary-fixed':              'var(--theme-on-tertiary-fixed, #221b00)',
        'primary-container':              'var(--theme-primary-container, #b40f1f)',
        'on-secondary-fixed':             'var(--theme-on-secondary-fixed, #1c1b1b)',
        'tertiary-fixed-dim':             'var(--theme-tertiary-fixed-dim, #e9c400)',
        'surface-container-highest':      'var(--theme-surface-container-highest, #353534)',
        'on-tertiary-fixed-variant':      'var(--theme-on-tertiary-fixed-variant, #544600)',
        'inverse-primary':                'var(--theme-inverse-primary, #bb1623)',
        'blood-accent':                   'var(--theme-blood-accent, #b01423)',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg:      '0.25rem',
        xl:      '0.5rem',
        full:    '0.75rem',
      },
      spacing: {
        'margin-mobile':   '16px',
        'margin-desktop':  '32px',
        'gutter':          '16px',
        'unit':            '4px',
        'container-max':   '1200px',
      },
      fontFamily: {
        'label-sm':           ['JetBrains Mono'],
        'system-code':        ['JetBrains Mono'],
        'headline-md':        ['Geist'],
        'headline-lg':        ['Geist'],
        'body-md':            ['Inter'],
        'headline-lg-mobile': ['Geist'],
        'body-lg':            ['Inter'],
      },
      fontSize: {
        'label-sm':           ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'system-code':        ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-md':        ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg':        ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md':            ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg-mobile': ['32px', { lineHeight: '36px', fontWeight: '700' }],
        'body-lg':            ['18px', { lineHeight: '28px', fontWeight: '400' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
