import React from 'react';
import styles from '../styles/Terms.module.css';

export default function Privacy() {
  return (
    <main className={styles.wrap}>
      <header className={styles.header}>
        <h1>Privacy Policy</h1>
        <p className={styles.updated}>
          Updated: <time dateTime="2025-09-01">2025-09-01</time>
        </p>
      </header>

      <nav className={styles.toc} aria-label="Table of contents">
        <h2 className={styles.tocTitle}>On this page</h2>
        <ul>
          <li><a href="#intro">Introduction</a></li>
          <li><a href="#definitions">Definitions &amp; key terms</a></li>
          <li><a href="#collect">What information we collect</a></li>
          <li><a href="#use">How we use information</a></li>
          <li><a href="#third-end">End-user info from third parties</a></li>
          <li><a href="#third-customer">Customer info from third parties</a></li>
          <li><a href="#sharing">Sharing with third parties</a></li>
          <li><a href="#when-where">Where &amp; when information is collected</a></li>
          <li><a href="#email">Email usage</a></li>
          <li><a href="#retention">How long we keep information</a></li>
          <li><a href="#security">How we protect information</a></li>
          <li><a href="#transfers">International transfers</a></li>
          <li><a href="#update-correct">Update/Correct information</a></li>
          <li><a href="#personnel">Personnel</a></li>
          <li><a href="#sale">Sale of Business</a></li>
          <li><a href="#affiliates">Affiliates</a></li>
          <li><a href="#law">Governing Law</a></li>
          <li><a href="#consent">Your Consent</a></li>
          <li><a href="#links">Links to Other Websites</a></li>
          <li><a href="#ads">Advertising</a></li>
          <li><a href="#cookies-ads">Cookies for Advertising</a></li>
          <li><a href="#cookies">Cookies</a></li>
          <li><a href="#blocking">Blocking/Disabling cookies</a></li>
          <li><a href="#remarketing">Remarketing Services</a></li>
          <li><a href="#kids">Kids’ Privacy</a></li>
          <li><a href="#changes">Changes to this Policy</a></li>
          <li><a href="#third-party">Third-Party Services</a></li>
          <li><a href="#fb-pixel">Facebook Pixel</a></li>
          <li><a href="#tracking">Tracking Technologies</a></li>
          <li><a href="#gdpr">GDPR</a></li>
          <li><a href="#rights">Data Subject Rights</a></li>
          <li><a href="#deletion">Data Deletion Requests</a></li>
          <li><a href="#contact">Contact Us</a></li>
        </ul>
      </nav>

      <article className={styles.content}>
        <section id="intro">
          <p>
            Erebus Portal (“we,” “our,” or “us”) is committed to protecting your privacy. This Privacy Policy
            explains how your personal information is collected, used, and disclosed by Erebus Portal.
          </p>
          <p>
            This Privacy Policy applies to our website and its associated subdomains (collectively, our “Service”)
            alongside our application, Erebus Portal. By accessing or using our Service, you signify that you have read,
            understood, and agree to our collection, storage, use, and disclosure of your personal information as described
            in this Privacy Policy and our Terms of Service. This Privacy Policy was created with
            <a href="https://termify.io" target="_blank" rel="noreferrer"> Termify</a>.
          </p>
        </section>

        <section id="definitions">
          <h2>Definitions and key terms</h2>
          <ul>
            <li><strong>Cookie:</strong> small amount of data generated by a website and saved by your web browser to identify your browser, provide analytics, and remember preferences or login info.</li>
            <li><strong>Company:</strong> Agile Advisors SING, Leof. Meg. Alexandrou 13, Egaleo 122 44 (controller responsible for your information under this Privacy Policy).</li>
            <li><strong>Country:</strong> Greece (where Erebus Portal or its owners/founders are based).</li>
            <li><strong>Customer:</strong> the company/organization/person that signs up to use the Erebus Portal Service to manage relationships with consumers or users.</li>
            <li><strong>Device:</strong> any internet-connected device (phone, tablet, computer, etc.).</li>
            <li><strong>IP address:</strong> a number assigned to a device connected to the Internet; it can often indicate approximate location.</li>
            <li><strong>Personnel:</strong> individuals employed by Erebus Portal or contracted to perform services.</li>
            <li><strong>Personal Data:</strong> information that directly or indirectly identifies a natural person (including identifiers like a personal number).</li>
            <li><strong>Service:</strong> the services provided by Erebus Portal on this platform.</li>
            <li><strong>Third-party service:</strong> advertisers, contest sponsors, promotional/marketing partners, and others who provide content or services we think may interest you.</li>
            <li><strong>Website:</strong> Erebus Portal’s site at <code>vtm.miketsak.gr</code>.</li>
            <li><strong>You:</strong> a person or entity registered with Erebus Portal to use the Services.</li>
          </ul>
        </section>

        <section id="collect">
          <h2>What Information Do We Collect?</h2>
          <p>We collect information when you visit our website/app, register, place an order, subscribe to our newsletter, respond to surveys, or fill out forms.</p>
          <ul>
            <li>Name / Username</li>
            <li>Email Address</li>
            <li>Mailing Address</li>
            <li>Age</li>
            <li>Password</li>
          </ul>
          <p>We also collect information from mobile devices to improve user experience (these features are optional).</p>
        </section>

        <section id="use">
          <h2>How Do We Use The Information We Collect?</h2>
          <ul>
            <li>Personalize your experience</li>
            <li>Improve our website/app and offerings</li>
            <li>Improve customer service</li>
            <li>Process transactions</li>
            <li>Administer contests, promotions, surveys, or features</li>
            <li>Send periodic emails</li>
          </ul>
        </section>

        <section id="third-end">
          <h2>When does Erebus Portal use end user information from third parties?</h2>
          <p>We collect End User Data necessary to provide the Erebus Portal services. End users may voluntarily provide social media information; we may collect publicly available data from those platforms subject to your privacy settings.</p>
        </section>

        <section id="third-customer">
          <h2>When does Erebus Portal use customer information from third parties?</h2>
          <p>We may receive information from third parties (e.g., automated fraud detection) when you contact us, and we may collect publicly available information on social media as allowed by your settings.</p>
        </section>

        <section id="sharing">
          <h2>Do we share the information we collect with third parties?</h2>
          <p>
            We may share personal and non-personal information with third parties such as advertisers, sponsors, promotional and marketing partners, affiliates, and business partners. In the event of a merger, asset sale, or reorganization, we may share or transfer information to successors-in-interest.
          </p>
          <p>
            We may engage trusted service providers for hosting, server/app maintenance, storage, email management, marketing storage, payment processing, customer service, and order fulfillment. We may share personal (and some non-personal) information with them so they can perform services for us and for you. We may share portions of log data (including IP addresses) with analytics partners, app developers, and ad networks for auditing, research, and reporting.
          </p>
          <p>
            We may also disclose information to government or law-enforcement officials or private parties as we deem necessary to comply with law or court orders, protect rights/safety, or prevent/stop illegal, unethical, or legally actionable activity.
          </p>
        </section>

        <section id="when-where">
          <h2>Where and when is information collected?</h2>
          <p>We collect personal information that you submit to us and may receive personal information about you from third parties as described above.</p>
        </section>

        <section id="email">
          <h2>How Do We Use Your Email Address?</h2>
          <p>
            By submitting your email on this website/app, you agree to receive emails from us. You can unsubscribe at any time via the opt-out link in our emails. We only email people who have authorized us directly or via a trusted third party. We may also use your email for customer-audience targeting on platforms (e.g., Facebook) where permitted.
          </p>
          <p>
            Emails provided only on the order processing page are used to send order-related information. If you provided the same email elsewhere, we may use it for the purposes stated in this Policy.
          </p>
        </section>

        <section id="retention">
          <h2>How Long Do We Keep Your Information?</h2>
          <p>We keep information only as long as needed to provide Erebus Portal to you and fulfill the purposes described here or to comply with legal/regulatory obligations. When no longer needed, we delete or de-identify it.</p>
        </section>

        <section id="security">
          <h2>How Do We Protect Your Information?</h2>
          <p>
            We use security measures (including TLS) when transmitting sensitive data. Payment details go to payment gateways and are accessible only to authorized parties. We do not store sensitive financial data after transactions. No method is 100% secure; absolute security cannot be guaranteed.
          </p>
        </section>

        <section id="transfers">
          <h2>Could my information be transferred to other countries?</h2>
          <p>Erebus Portal is incorporated in Greece. Information collected via our website, direct interactions, or support may be transferred and hosted worldwide, including in countries without general data-transfer laws. By using the Service, you consent to such transfers as allowed by law.</p>
        </section>

        <section id="update-correct">
          <h2>Can I update or correct my information?</h2>
          <p>
            Your rights depend on your relationship with us. Personnel update/correct data per internal HR policies. Customers can contact us to (1) update/correct personal information, (2) change communication preferences, or (3) request deletion by cancelling the account. We may verify identity before changes. Some backups/archives are not feasibly editable or erasable, but we will act promptly where reasonably practicable. End users of our customers should contact the relevant organization.
          </p>
        </section>

        <section id="personnel">
          <h2>Personnel</h2>
          <p>If you are a worker or applicant, we process the information you voluntarily provide for HR purposes (benefits administration, screening), per applicable law.</p>
        </section>

        <section id="sale">
          <h2>Sale of Business</h2>
          <p>We may transfer information to a third party in a sale, merger, or other transfer of all/substantially all assets, provided the recipient agrees to adhere to this Privacy Policy.</p>
        </section>

        <section id="affiliates">
          <h2>Affiliates</h2>
          <p>We may disclose information (including personal information) to Corporate Affiliates (entities under common control). Such affiliates will treat your information in accordance with this Policy.</p>
        </section>

        <section id="law">
          <h2>Governing Law</h2>
          <p>This Privacy Policy is governed by the laws of Greece without regard to conflict-of-laws rules. You may have additional rights under applicable frameworks.</p>
        </section>

        <section id="consent">
          <h2>Your Consent</h2>
          <p>By using the website/app, registering an account, or making a purchase, you consent to this Privacy Policy and agree to its terms.</p>
        </section>

        <section id="links">
          <h2>Links to Other Websites</h2>
          <p>This Policy applies only to our Services. External sites have their own rules and policies. When you leave our Services, their terms and privacy policies apply.</p>
        </section>

        <section id="ads">
          <h2>Advertising</h2>
          <p>This website/app may display third-party ads and links. We do not accept liability for third-party content, conduct, or offerings.</p>
        </section>

        <section id="cookies-ads">
          <h2>Cookies for Advertising</h2>
          <p>These cookies track activity across services for interest-based advertising (e.g., relevance, frequency capping, proper display for advertisers).</p>
        </section>

        <section id="cookies">
          <h2>Cookies</h2>
          <p>We use Cookies to enhance performance and functionality. Disabling Cookies may break certain features (e.g., videos, stay-logged-in) and require re-entering credentials.</p>
        </section>

        <section id="blocking">
          <h2>Blocking and disabling cookies and similar technologies</h2>
          <p>Browsers can block cookies/technologies, which may prevent essential features from working and remove saved preferences. Deleting cookies is done in your browser settings.</p>
        </section>

        <section id="remarketing">
          <h2>Remarketing Services</h2>
          <p>We may use remarketing (retargeting) to show ads to people who previously visited our site on the websites/platforms they use.</p>
        </section>

        <section id="kids">
          <h2>Kids' Privacy</h2>
          <p>We do not knowingly collect information from children under 13. If you believe a child has provided Personal Data, contact us so we can remove it.</p>
        </section>

        <section id="changes">
          <h2>Changes To Our Privacy Policy</h2>
          <p>We may update this Policy to reflect service or policy changes. Where required, we’ll notify you before changes take effect. Continued use indicates acceptance.</p>
        </section>

        <section id="third-party">
          <h2>Third-Party Services</h2>
          <p>We may display, include, or link to third-party content/services. Use is at your own risk, under those third parties’ terms and policies.</p>
        </section>

        <section id="fb-pixel">
          <h2>Facebook Pixel</h2>
          <p>We may use Facebook Pixel to measure ad effectiveness by understanding actions taken on our website, in line with Facebook’s privacy policy.</p>
        </section>

        <section id="tracking">
          <h2>Tracking Technologies</h2>
          <ul>
            <li><strong>Google Maps API:</strong> can be used to display maps, plan routes, and more; it may collect device/security information per Google’s privacy policy.</li>
            <li><strong>Cookies:</strong> enhance performance and functionality.</li>
            <li><strong>Local Storage:</strong> client-side storage with greater capacity than cookies; no data in HTTP headers.</li>
            <li><strong>Sessions:</strong> used to identify visited areas of our website.</li>
          </ul>
        </section>

        <section id="gdpr">
          <h2>Information about General Data Protection Regulation (GDPR)</h2>
          <p>For users in the EEA, GDPR governs how personal data is processed and grants rights to individuals.</p>
          <h3>What is personal data?</h3>
          <p>Any data relating to an identified or identifiable person (e.g., financial info, political opinions, genetic/biometric data, IP, address, sexual orientation, ethnicity).</p>
          <ul>
            <li>Processing must be fair, lawful, and transparent; used for specified purposes only.</li>
            <li>Data must be kept no longer than necessary.</li>
            <li>Individuals have rights to access, copy, update, delete, restrict, or port their data.</li>
          </ul>
        </section>

        <section id="rights">
          <h2>Individual Data Subject's Rights — Data Access, Portability and Deletion</h2>
          <p>
            We use vetted, DPA-compliant vendors. We may store conversation and personal data for up to 6 years unless your
            account is deleted, in which case we dispose of data in accordance with our Terms of Service and this Policy and
            do not hold it longer than necessary.
          </p>
        </section>

        <section id="deletion">
          <h2>Data Deletion Requests</h2>
          <p>
            If you want your account data (email, username, password) deleted, contact
            {' '}<a href="mailto:info@agileadvisors.gr">info@agileadvisors.gr</a>. Upon verifiable request, we will delete your
            personal data within <strong>6 months</strong>, except where retention is required by law, dispute resolution, fraud
            prevention, or other legitimate purposes permitted by law.
          </p>
        </section>

        <section id="contact">
          <h2>Contact Us</h2>
          <p>Don't hesitate to contact us if you have any questions.</p>
          <ul>
            <li>Email: <a href="mailto:info@agileadvisors.gr">info@agileadvisors.gr</a></li>
            <li>Website: <a href="https://agileadvisors.gr/" target="_blank" rel="noreferrer">https://agileadvisors.gr/</a></li>
          </ul>
        </section>
      </article>
    </main>
  );
}
