"use client"
// Auto-generated by boneyard vite plugin — do not edit
import { registerBones } from 'boneyard-js/react'

import _admin_users_tab from './admin-users-tab.bones.json'
import _announcements_view from './announcements-view.bones.json'
import _boons_page from './boons-page.bones.json'
import _character_view_loading from './character-view-loading.bones.json'
import _court_hierarchy from './court-hierarchy.bones.json'
import _domains_page from './domains-page.bones.json'
import _downtimes_page from './downtimes-page.bones.json'
import _home_page from './home-page.bones.json'
import _news_page from './news-page.bones.json'
import _premonitions_page from './premonitions-page.bones.json'
import _schrecknet_page from './schrecknet-page.bones.json'
import _surfaceweb_page from './surfaceweb-page.bones.json'

registerBones({
  "admin-users-tab": _admin_users_tab,
  "announcements-view": _announcements_view,
  "boons-page": _boons_page,
  "character-view-loading": _character_view_loading,
  "court-hierarchy": _court_hierarchy,
  "domains-page": _domains_page,
  "downtimes-page": _downtimes_page,
  "home-page": _home_page,
  "news-page": _news_page,
  "premonitions-page": _premonitions_page,
  "schrecknet-page": _schrecknet_page,
  "surfaceweb-page": _surfaceweb_page,
})
